version: 2

jobs:
  build:
    docker:
      # The Node version should always match what's in .nvmrc.
      - image: cimg/node:18.18.1
    working_directory: ~/repo
    steps:
      - checkout
      # Install 
      - run:
          name: Install dependencias 
          command: |
            npm install
  image:
    docker:
      # The Node version should always match what's in .nvmrc.
      - image: cimg/node:18.18.1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS 
    working_directory: ~/repo
    steps:
      - checkout
      # Install
      - run: npm install
      # Build Docker Image
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker:   # (2)
          docker_layer_caching: false  # (3)
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t cboard/cboard-wiki:$TAG -t cboard/cboard-wiki:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push cboard/cboard-wiki:latest
          docker push cboard/cboard-wiki:$TAG
workflows:
  version: 2
  build_image:
    jobs:
      - build:
          context: wiki
      - image:
          context: wiki
          requires:
            - build
          filters:
            branches:
              
